#
# Binary Sensor
#
# https://www.home-assistant.io/integrations/binary_sensor/
#

binary_sensor:
  # Workday
  - platform: workday
    country: UA
  # Humidifier
  - platform: template
    sensors:
      humidifier_no_watter:
        friendly_name: "Humidifier No Watter"
        value_template: >-
          {{ state_attr('fan.humidifier', 'no_water') }}
