- platform: template
  sensors:
    anyone_home:
      device_class: occupancy
      friendly_name: "Anyone Home"
      value_template: >-
        {{
          is_state('person.denys', 'home') or
          is_state('person.marry', 'home')
        }}
