#
# Binary Sensor
#
# https://www.home-assistant.io/integrations/binary_sensor/
#

binary_sensor:
  # Workday
  - platform: workday
    country: UA
  # Times of the Day
  - platform: tod
    name: Activity Time
    after: '13:00'
    before: '19:00'
  - platform: tod
    name: Evening Time
    after: sunset
    before: '23:00'
  - platform: tod
    name: Night Time
    after: '23:00'
    before: '1:00'
  - platform: tod
    name: Do Not Disturb
    after: '01:00'
    before: '9:00'
