#
# Home Assistant
#
# https://www.home-assistant.io/integrations/homeassistant/
#

homeassistant:
  # Load customizations
  # Only for those device that are not customisable from UI
  customize: !include_dir_merge_named customizations
