#
# Sensor
#
# https://www.home-assistant.io/integrations/sensor/
#

sensor:
  # MQTT Bridge
  - platform: mqtt
    name: Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
  # System Monitor
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: swap_use_percent
      - type: processor_use
      - type: memory_use_percent
  # Humidifier
  - platform: template
    sensors:
      humidifier_humidity:
        friendly_name: "Humidifier Humidity"
        unit_of_measurement: '%'
        device_class: humidity
        value_template: >-
          {{ state_attr('fan.humidifier', 'humidity') }}
      humidifier_temperature:
        friendly_name: "Humidifier Temperature"
        unit_of_measurement: '°C'
        device_class: temperature
        value_template: >-
          {{ state_attr('fan.humidifier', 'temperature') }}
  # Purifier
  - platform: template
    sensors:
      purifier_humidity:
        value_template: >-
          {{ state_attr('fan.purifier', 'humidity') }}
      purifier_temperature:
        value_template: >-
          {{ state_attr('fan.purifier', 'temperature') | round(2) }}
      purifier_aqi:
        value_template: >-
          {{ state_attr('fan.purifier', 'aqi') }}
  # Eco City AQI
  - platform: rest
    name: nyvky_aqi
    resource: https://eco-city.org.ua/public.json?id=876&timeShift=0
    value_template: >-
      {{ value_json[0].index }}
    json_attributes_path: "$.[0]"
    json_attributes:
      - name
      - unit
      - value
      - localName
      - localUnit
      - time
      - index
  # Kyiv Smart Card
  - platform: rest
    name: kyivsmartcard_denys
    resource: https://my.kyivcity.gov.ua/api/me/travel-cards
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
      Connection: keep-alive
      Authorization: !secret kyivsmartcard_denys_token
    value_template: >-
      {{ value_json[0].assets.purchases[0].residualUnits }}
    json_attributes_path: "$.[0]"
    json_attributes:
      - code
      - name
      - createdAt
  - platform: rest
    name: kyivsmartcard_marry
    resource: https://my.kyivcity.gov.ua/api/me/travel-cards
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
      Connection: keep-alive
      Authorization: !secret kyivsmartcard_marry_token
    value_template: >-
      {{ value_json[0].assets.purchases[0].residualUnits }}
    json_attributes_path: "$.[0]"
    json_attributes:
      - code
      - name
      - createdAt
