# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Device Discovery
discovery:

# Home Assistant
homeassistant:
  name: Kyiv Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  time_zone: Europe/Kiev #KyivNotKiev
  unit_system: metric
  customize: !include customize.yaml

# HTTP
http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Text to speech
tts:
  - platform: google_translate

homekit:
  filter:
    include_entities:
      - light.ceiling_light_light
      - light.table_lights
      - switch.bed_lights
      - switch.tv_lights
      - binary_sensor.bedroom_movement_sensor_occupancy
      - binary_sensor.living_room_movement_sensor_occupancy
      - binary_sensor.front_door_sensor_contact
      - input_boolean.zigbee_permit_join
      - media_player.samsung_tv
  entity_config:
    binary_sensor.bedroom_movement_sensor_occupancy:
      linked_battery_sensor: sensor.bedroom_movement_sensor_battery
    binary_sensor.living_room_movement_sensor_occupancy:
      linked_battery_sensor: sensor.living_room_movement_sensor_battery
    binary_sensor.front_door_sensor_contact:
      linked_battery_sensor: sensor.front_door_sensor_battery
    input_boolean.zigbee_permit_join:
      name: Zigbee Pairing

google_assistant:
  project_id: !secret google_project_id
  service_account: !secret google_service_account
  report_state: true
  exposed_domains:
    - light
    - switch
    - input_boolean
    - scene
    - media_player
  entity_config:
    input_boolean.zigbee_permit_join:
      name: Zigbee Pairing
      room: Living Room
    media_player.samsung_tv:
      name: TV
      aliases:
        - Samsung TV

mqtt:
  broker: core-mosquitto
  discovery: true
  discovery_prefix: homeassistant
  username: !secret mqtt_user
  password: !secret mqtt_password

group: !include groups.yaml
light: !include light.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
media_player: !include media_player.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
timer: !include timer.yaml
sensor: !include sensor.yaml
