#
# Welcome to my Home Assistant configuration!
#
# This file is only used to bootstrap the system.
# You can find the rest of the configurationo inside the integrations folder.
#

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Load Home Assistant integrations as packages
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
