# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Kyiv Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  customize: !include customize.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Text to speech
tts:
  - platform: google_translate

homekit:
  filter:
    include_entities:
      - light.ceiling_light_light
      - light.table_lights
      - switch.koogeek_p1_b50dfe
      - switch.koogeek_p1_b5130f

google_assistant:
  project_id: !secret google_project_id
  service_account: !secret google_service_account
  report_state: true

mqtt:
  broker: core-mosquitto
  discovery: true
  discovery_prefix: homeassistant
  username: !secret mqtt_user
  password: !secret mqtt_password

binary_sensor:
  - platform: template
    sensors:
      anyone_home:
        device_class: occupancy
        friendly_name: "Anyone Home"
        value_template: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"

group: !include groups.yaml
light: !include light.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_boolean: !include input_boolean.yaml
timer: !include timer.yaml
sensor: !include sensor.yaml
