version: '3.6'
services:
  # Portainer CE
  # Managing containers via nice web UI
  portainer-ce:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - 8000:8000 # Agent
      - 9000:9000 # Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .docker/portainer-ce/data:/data

  # Home Assistant
  # The core of my smart-home automations
  home-assistant:
    container_name: home-assistant
    image: homeassistant/${HOME_ASSISTANT_IMAGE}
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: unless-stopped
    network_mode: host

  # MQTT
  # A Mosquitto broker for my devices communicating via MQTT
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1888:1883
    volumes:
      - .docker/mosquitto/data:/mosquitto/data
      - .docker/mosquitto/log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # Zigbee2MQTT
  # A bridge for zigbee devices to be able to communicate via MQTT
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .docker/zigbee2mqtt/log:/app/data/log
      - /run/udev:/run/udev:ro
      - ./zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml
      - ./zigbee2mqtt/secret.yaml:/app/data/secret.yaml
    ports:
      - 8099:8099
    # devices:
    # - /dev/ttyAMA0:/dev/ttyACM0
    #- /dev/ttyACM0
    privileged: true

  # Duplicati
  # Simple and flexible UI for backing up stuff
  duplicati:
    container_name: duplicati
    image: linuxserver/duplicati
    env_file:
      - .env
    volumes:
      - .docker/duplicati/config:/config #Config Files
      - .backups:/backups
      - .:/source
    ports:
      - 8200:8200
    restart: unless-stopped

  # MariaDB
  # A database for Home Assistant, Nginx Proxy Manager and Umami
  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    volumes:
      - .docker/mariadb/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - .env

  # Adminer
  # A dead-simple database manager
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

  # Nginx Proxy Manager
  # Nice and simple Nginx UI for managing reverce proxy
  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80' # HTTP port
      - '443:443' # HTTPS port
      - '8081:81' # Admin Paner port
    environment:
      DB_MYSQL_HOST: ${MYSQL_HOST}
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: 'nginxproxymanager'
    volumes:
      - .docker/nginx-proxy-manager/data:/data
      - .docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  # AirConnect
  # Make AirPlay available for Chromecast devices
  airconnect:
    container_name: airconnect
    image: 1activegeek/airconnect
    restart: unless-stopped
    network_mode: host

  # samba:
  #   container_name: samba
  #   image: dperson/samba
  #   volumes:
  #     - .:/mnt
  #   ports:
  #     - '139:139'
  #     - '445:445'
  #     - '137:137/udp'
  #     - '138:138/udp'
  #   command: samba.sh -s "smart-home;/mnt;yes;no;no;all" -u ${SAMBA_USER};${SAMBA_PASSWORD}
  #   restart: unless-stopped

  # AdGuard Home
  # Ad-blocking DNS server
  # adguard:
  #   container_name: adguard
  #   image: adguard/adguardhome
  #   restart: unless-stopped
  #   # networks:
  #   # - adguard
  #   ports:
  #     # uncomment on real machine
  #     # - '53:53/tcp'
  #     # - '53:53/udp'
  #     - '67:67/udp'
  #     - '68:68/tcp'
  #     - '68:68/udp'
  #     - '853:853/tcp'
  #     - '8300:3000/tcp'
  #   volumes:
  #     - .docker/adguard/work:/opt/adguardhome/work
  #     - .docker/adguard/conf:/opt/adguardhome/conf

  # Plex
  # Personal media server with movies and tv-series
  # plex:
  #   image: linuxserver/plex
  #   container_name: plex
  #   network_mode: host
  #   env_file:
  #     - .env
  #   environment:
  #     - VERSION=docker
  #     # TODO: plex claim
  #   volumes:
  #     - .docker/plex/config:/config
  #     - ./media:/media
  #   restart: unless-stopped

  # Transmission
  # A torrent client for downloading media
  # transmission:
  #   container_name: transmission
  #   image: linuxserver/transmission
  #   env_file:
  #     - .env
  #   environment:
  #     - USER=${TRANSMISSION_USER}
  #     - PASS=${TRANSMISSION_PASSWORD}
  #   volumes:
  #     - .docker/transmission/config:/config
  #     - .docker/transmission/downloads:/downloads # change this to match media folder
  #     - .docker/transmission/watch:/watch # change this to match media folder
  #   ports:
  #     - '9091:9091'
  #     - '51413:51413'
  #     - '51413:51413/udp'
  #   restart: unless-stopped

  # Umami.is
  # A self-hosted analytics for my websites
  # umami:
  #   container_name: umami
  #   image: ghcr.io/mikecao/umami:mysql-latest
  #   ports:
  #     - '8300:3000'
  #   environment:
  #     DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/umami
  #     DATABASE_TYPE: mysql
  #     HASH_SALT: ${UMAMI_HASH_SALT}
  #   depenversion: '3.6'
