# TODO: Move this to lovelace after merging of https://github.com/home-assistant/core/pull/37561

title: Дім
views:
  - path: home
    title: Дім
    icon: mdi:home
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_columns: 3
        cards:
          - type: markdown
            content: >
              {% set greeting = [
                  'Вітаю вдома',
                  'Привіт'
                ] | random
              %}

              ## {{ greeting }}, {{ user }}!
          - type: horizontal-stack
            cards:
              - type: picture-entity
                name: Денис
                entity: person.denys
                image: /local/images/denys.jpg
                state_filter:
                  home: none
                  wix: brightness(90%) sepia(100%) hue-rotate(15deg)
                  citrusdev: brightness(90%) sepia(70%) hue-rotate(0deg) saturate(200%)
                  away: grayscale(1)
              - type: picture-entity
                name: Маша
                entity: person.marry
                image: /local/images/marry.jpg
                state_filter:
                  home: none
                  wix: brightness(90%) sepia(100%) hue-rotate(15deg)
                  citrusdev: brightness(90%) sepia(70%) hue-rotate(0deg) saturate(200%)
                  away: grayscale(1)
          - type: map
            entities:
              - person.marry
              - person.denys
            hours_to_show: 12
            default_zoom: 13

          - break

          - type: weather-forecast
            entity: weather.nyvky
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Температура вдома
                entities:
                  - sensor.home_temperature
                line_color: '#E53935'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true
              - type: custom:mini-graph-card
                name: Вологість вдома
                entities:
                  - sensor.home_humidity
                line_color: '#2AD4FF'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Тиск вдома
                entities:
                  - sensor.living_room_conditions_sensor_pressure
                line_color: '#5167ed'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true
              - type: custom:mini-graph-card
                name: UV-індекс
                entities:
                  - sensor.current_uv_index
                # line_color: '#FFD700'
                hours_to_show: 12
                points_per_hour: 1
                color_thresholds:
                  - value: 0
                    color: '#FFD700'
                  - value: 6
                    color: '#F9A825'
                  - value: 8
                    color: '#EF6C00'
                  - value: 11
                    color: '#B71C1C'
                  - value: 20
                    color: '#6A1B9A'
                animate: true
                hour24: true
                show:
                  graph: bar
          - type: 'custom:mini-graph-card'
            name: Якість повітря
            entities:
              - entity: sensor.purifier_aqi
                show_state: true
                state_adaptive_color: true
              - entity: sensor.nyvky_aqi
                show_state: true
                state_adaptive_color: true
                color: '#a8a8a8'
            points_per_hour: 2
            hours_to_show: 12
            color_thresholds:
              - value: 50
                color: '#17a355'
              - value: 100
                color: '#e9d109'
              - value: 200
                color: '#ea270d'
              - value: 300
                color: '#7c2c85'
              - value: 600
                color: '#66001f'
            animate: true
            hour24: true
          
          - break

          - type: horizontal-stack
            cards:
              - type: entities
                title: Вітальня
                entities:
                  - entity: light.living_room_table_lights
                  - entity: light.living_room_tv_lights
                  - entity: light.living_room_main_lights
              - type: entities
                title: Спальня
                entities:
                  - entity: light.bedroom_ceiling_light_light
                  - entity: light.bedroom_bed_lights
                  - entity: light.bedroom_floor_lamp
          - type: horizontal-stack
            cards:
              - type: button
                name: Без світла
                entity: scene.lights_out
                icon_height: 40px
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.lights_out
                hold_action:
                  action: more-info
              - type: button
                name: Нічне
                entity: scene.night_lights
                icon_height: 40px
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.night_lights
                hold_action:
                  action: more-info
              - type: button
                name: Вечірнє
                entity: scene.evening_lights
                icon_height: 40px
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.evening_lights
                hold_action:
                  action: more-info
              - type: button
                name: Яскраве
                entity: scene.bright_lights
                icon_height: 40px
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bright_lights
                hold_action:
                  action: more-info
          - type: horizontal-stack
            cards:
              - type: button
                name: Адаптивне
                entity: switch.flux
                icon_height: 40px
              - type: button
                name: Активне
                entity: scene.active_lights
                icon_height: 40px
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.active_lights
                hold_action:
                  action: more-info
              - type: button
                name: Романтичне
                entity: scene.romantic_lights
                icon_height: 40px
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.romantic_lights
                hold_action:
                  action: more-info

  - path: living-room
    title: Вітальня
    icon: mdi:sofa
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_collumns: 3
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Температура у вітальні
                entities:
                  - sensor.living_room_temperature
                line_color: '#E53935'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true
              - type: custom:mini-graph-card
                name: Вологість у вітальні
                entities:
                  - sensor.living_room_humidity
                line_color: '#2AD4FF'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true

  - path: bedroom
    title: Спальня
    icon: mdi:bed-empty
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_collumns: 3
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Температура у спальні
                entities:
                  - sensor.bedroom_temperature
                line_color: '#E53935'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true
              - type: custom:mini-graph-card
                name: Вологість у спальні
                entities:
                  - sensor.bedroom_humidity
                line_color: '#2AD4FF'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true

  - path: vacuum
    title: Пилосос
    icon: mdi:robot-vacuum
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_collumns: 2
        cards:
          - type: 'custom:vacuum-card'
            entity: vacuum.roborock
            compact_view: false
            actions:
              - icon: 'mdi:sofa'
                name: Living Room
                service: script.vacuum_clean_living_room
              - icon: 'mdi:silverware-fork-knife'
                name: Kitchen
                service: script.vacuum_clean_kitchen
              - icon: 'mdi:bed-empty'
                name: Bedroom
                service: script.vacuum_clean_bedroom
              - icon: 'mdi:hanger'
                name: Corridor
                service: script.vacuum_clean_corridor
              - icon: 'mdi:shower'
                name: Bathroom
                service: script.vacuum_clean_bathroom
            stats:
              cleaning:
                - attribute: cleaned_area
                  subtitle: Площа прибирання
                  unit: м²
                - attribute: cleaning_time
                  subtitle: Час прибирання
                  unit: хв
              default:
                - attribute: filter_left
                  subtitle: Фільтр
                  unit: год
                - attribute: side_brush_left
                  subtitle: Бокова щітка
                  unit: год
                - attribute: main_brush_left
                  subtitle: Головна щітка
                  unit: год
                - attribute: sensor_dirty_left
                  subtitle: Сенсори
                  unit: год

          - type: entities
            entities:
              - entity: script.vacuum_access
                name: Виїхати з-під ліжка
                action_name: Виїхати
                secondary_info: last-triggered
              - entity: script.vacuum_maintenance
                name: Обслуговування пилососа
                action_name: Обслужити
                secondary_info: last-triggered

          - break

          - type: 'custom:xiaomi-vacuum-map-card'
            entity: vacuum.roborock
            map_image: /local/images/floorplan.png
            default_mode: go_to_target
            debug: false
            language: uk
            calibration_points:
              - map:
                  x: 360
                  y: 720
                vacuum:
                  x: 24500
                  y: 24500
              - map:
                  x: 740
                  y: 345
                vacuum:
                  x: 28000
                  y: 28000
              - map:
                  x: 340
                  y: 345
                vacuum:
                  x: 24000
                  y: 28000

  - path: car
    title: Автомобіль
    icon: mdi:car
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_collumns: 2
        cards:
          - type: entities
            title: Сигналізація
            state_color: true
            show_header_toggle: false
            entities:
              - lock.toyota_security
              - switch.toyota_horn
              - switch.toyota_engine
          - type: map
            entities:
              - device_tracker.toyota_location
            hours_to_show: 24
            default_zoom: 13
            aspect_ratio: 16x13.3 # Maintain size of a row
          
          - break

          - type: entities
            title: Датчики
            entities:
              - sensor.toyota_balance
              - binary_sensor.toyota_doors
              - binary_sensor.toyota_hood
              - binary_sensor.toyota_trunk
              - binary_sensor.toyota_alarm
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Температура салону
                entities:
                  - sensor.toyota_interior_temperature
                line_color: '#E53935'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true
              - type: custom:mini-graph-card
                name: Температура двигуна
                entities:
                  - sensor.toyota_engine_temperature
                line_color: '#f9bb10'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Акумулятор
                entities:
                  - sensor.toyota_battery
                line_color: '#2AD4FF'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true
              - type: custom:mini-graph-card
                name: Сигнал GSM
                entities:
                  - sensor.toyota_gsm_signal
                line_color: '#08F900'
                hours_to_show: 12
                points_per_hour: 2
                animate: true
                hour24: true

  - path: cameras
    title: Камери
    icon: mdi:video-box
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_collumns: 2
        cards:
          - type: picture-glance
            title: Софійська площа
            camera_image: camera.sofiyska
            camera_view: live
            aspect_ratio: 50%
            entities: []
            hold_action:
              action: call-service
              service: script.stream_camera_to_apple_tv
              service_data:
                camera: camera.sofiyska

          - break

          - type: picture-glance
            title: Чернівці
            camera_image: camera.chernivtsi
            camera_view: live
            aspect_ratio: 50%
            entities: []
            hold_action:
              action: call-service
              service: script.stream_camera_to_apple_tv
              service_data:
                camera: camera.chernivtsi

  - path: system
    title: Система
    icon: 'mdi:chip'
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        max_collumns: 3
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.speedtest_download
                line_color: '#76FF8D'
                hours_to_show: 24
                points_per_hour: 2
                animate: true
                hour24: true
                extrema: true
              - type: custom:mini-graph-card
                entities:
                  - sensor.speedtest_upload
                line_color: '#FF71B2'
                hours_to_show: 24
                points_per_hour: 2
                animate: true
                hour24: true
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Пінг
                entities:
                  - sensor.speedtest_ping
                line_color: '#2de5d1'
                hours_to_show: 24
                points_per_hour: 2
                animate: true
                hour24: true
                show:
                  graph: bar
              - type: custom:mini-graph-card
                name: Пристроїв підключено
                entities:
                  - sensor.asuswrt_devices_connected
                line_color: '#FFDE59'
                hours_to_show: 24
                aggregate_func: first
                animate: true
                hour24: true
                show:
                  graph: bar
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Процесор
                entity: sensor.processor_use
                severity:
                  green: 0
                  yellow: 50
                  red: 75
              - type: gauge
                name: Оперативна пам’ять
                entity: sensor.memory_use_percent
                severity:
                  green: 0
                  yellow: 50
                  red: 75
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Диск
                entity: sensor.disk_use_percent
                severity:
                  green: 0
                  yellow: 75
                  red: 90
              - type: gauge
                name: Swap
                entity: sensor.swap_use_percent
                severity:
                  green: 0
                  yellow: 75
                  red: 90

          - break

          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.adguard_dns_queries
                line_color: '#33DBFF'
                hours_to_show: 24
                animate: true
                hour24: true
                group_by: hour
                aggregate_func: delta
              - type: custom:mini-graph-card
                entities:
                  - sensor.adguard_dns_queries_blocked
                line_color: '#FF5733'
                hours_to_show: 24
                points_per_hour: 2
                animate: true
                hour24: true
                group_by: hour
                aggregate_func: delta
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.adguard_average_processing_speed
                line_color: '#75FF33'
                hours_to_show: 24
                animate: true
                hour24: true
              - type: custom:mini-graph-card
                entities:
                  - sensor.adguard_dns_queries_blocked_ratio
                line_color: '#BD33FF'
                hours_to_show: 24
                points_per_hour: 2
                animate: true
                hour24: true
          - type: entities
            title: AdGuard DNS
            entities:
              - switch.adguard_protection
              - switch.adguard_filtering
              - switch.adguard_parental_control
              - switch.adguard_safe_browsing
              - switch.adguard_safe_search

          - break

          - type: entities
            title: Zigbee Bridge
            entities:
              - input_boolean.zigbee_permit_join
              - timer.zigbee_permit_join
              - sensor.bridge_state
