title: Home
views:
  - badges:
      - entity: binary_sensor.updater
      - entity: binary_sensor.workday_sensor
      - entity: person.denys
      - entity: person.marry
      - entity: sensor.denys_iphone_battery_level
      - entity: sensor.maria_iphone_battery_level
      - entity: sun.sun
      - entity: sensor.living_room_conditions_sensor_temperature
    cards:
      - entity: weather.nyvky
        type: weather-forecast
      - entities:
          - entity: light.living_room_tv_lights
          - entity: light.living_room_table_lights
          - entity: light.living_room_main_lights
          - entity: light.bedroom_bed_lights
          - entity: light.bedroom_ceiling_light_light
          - entity: light.bedroom_floor_lamp
        title: Lights
        type: entities
      - actions:
          - icon: 'mdi:sofa'
            name: Living Room
            service: script.vacuum_clean_living_room
          - icon: 'mdi:silverware-fork-knife'
            name: Kitchen
            service: script.vacuum_clean_kitchen
          - icon: 'mdi:bed-empty'
            name: Bedroom
            service: script.vacuum_clean_bedroom
          - icon: 'mdi:hanger'
            name: Corridor
            service: script.vacuum_clean_corridor
          - icon: 'mdi:shower'
            name: Bathroom
            service: script.vacuum_clean_bathroom
        compact_view: false
        entity: vacuum.roborock
        image: default
        stats:
          cleaning:
            - attribute: cleaned_area
              subtitle: Площа прибирання
              unit: м²
            - attribute: cleaning_time
              subtitle: Час прибирання
              unit: хв
          default:
            - attribute: filter_left
              subtitle: Фільтр
              unit: год
            - attribute: side_brush_left
              subtitle: Бокова щітка
              unit: год
            - attribute: main_brush_left
              subtitle: Головна щітка
              unit: год
            - attribute: sensor_dirty_left
              subtitle: Сенсори
              unit: год
        type: 'custom:vacuum-card'
      - cards:
          - entity: media_player.google_home_mini
            type: media-control
          - entity: media_player.samsung_tv
            type: media-control
          - entity: media_player.apple_tv
            type: media-control
          - entity: media_player.playstation_4
            type: media-control
        type: vertical-stack
      - entities:
          - entity: binary_sensor.living_room_movement_sensor_occupancy
          - entity: binary_sensor.bedroom_movement_sensor_occupancy
          - entity: binary_sensor.front_door_sensor_contact
        title: Presence
        type: entities
      - type: 'custom:mini-graph-card'
        entities:
          - entity: sensor.nyvky_aqi
            show_state: false
            state_adaptive_color: true
          - entity: sensor.purifier_aqi
            show_state: true
            state_adaptive_color: true
        points_per_hour: 1
        animate: true
        hour24: true
      - cards:
          - entity: sensor.living_room_conditions_sensor_temperature
            graph: line
            type: sensor
          - detail: 2
            entity: sensor.living_room_conditions_sensor_humidity
            graph: line
            type: sensor
          - detail: 2
            entity: sensor.living_room_conditions_sensor_pressure
            graph: line
            type: sensor
        type: vertical-stack
      - entities:
          - entity: fan.humidifier
          - entity: sensor.humidifier_temperature
          - entity: sensor.humidifier_humidity
          - entity: fan.purifier
          - entity: sensor.purifier_temperature
          - entity: sensor.purifier_humidity
          - entity: sensor.purifier_aqi
        title: Humidifier
        type: entities
    panel: false
    path: home
    title: Home
  - badges: []
    cards:
      - dark_mode: false
        default_zoom: 15
        entities:
          - entity: person.marry
          - entity: person.denys
        hours_to_show: 24
        type: map
    icon: 'mdi:map-marker-path'
    panel: true
    path: location-history
    title: Location History
  - badges: []
    cards:
      - calibration_points:
          - map:
              x: 360
              'y': 720
            vacuum:
              x: 24500
              'y': 24500
          - map:
              x: 740
              'y': 345
            vacuum:
              x: 28000
              'y': 28000
          - map:
              x: 340
              'y': 345
            vacuum:
              x: 24000
              'y': 28000
        debug: false
        default_mode: go_to_target
        entity: vacuum.roborock
        map_image: /local/images/floorplan.png
        type: 'custom:xiaomi-vacuum-map-card'
    icon: 'mdi:robot-vacuum'
    path: vacuum-map
  - badges: []
    cards:
      - aspect_ratio: 50%
        camera_image: camera.sofiyska
        camera_view: live
        entities: []
        hold_action:
          action: call-service
          service: script.stream_camera_to_apple_tv
          service_data:
            camera: camera.sofiyska
        image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
        title: Софійська площа
        type: picture-glance
      - aspect_ratio: 50%
        camera_image: camera.peremohy
        camera_view: live
        entities: []
        hold_action:
          action: call-service
          service: script.stream_camera_to_apple_tv
          service_data:
            camera: camera.peremohy
        image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
        title: Площа перемоги
        type: picture-glance
      - aspect_ratio: 50%
        camera_image: camera.chernivtsi
        camera_view: live
        entities: []
        hold_action:
          action: call-service
          service: script.stream_camera_to_apple_tv
          service_data:
            camera: camera.chernivtsi
        image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
        title: Чернівці
        type: picture-glance
    icon: 'mdi:camcorder'
    path: cameras
    title: Cameras
  - badges: []
    cards:
      - cards:
          - cards:
              - detail: 2
                entity: sensor.adguard_dns_queries
                graph: line
                hours_to_show: 24
                type: sensor
              - detail: 2
                entity: sensor.adguard_dns_queries_blocked
                graph: line
                type: sensor
            type: horizontal-stack
          - entities:
              - entity: sensor.adguard_average_processing_speed
              - entity: sensor.adguard_dns_queries_blocked_ratio
              - entity: switch.adguard_protection
              - entity: switch.adguard_filtering
              - entity: switch.adguard_parental_control
              - entity: switch.adguard_safe_browsing
              - entity: switch.adguard_safe_search
            title: AdGuard
            type: entities
        type: vertical-stack
    icon: 'mdi:chip'
    path: system
    title: System
