- id: automatic_theme_change
  alias: Automatic Theme Change
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            default
          {% else %}
            midnight
          {% endif %}

- alias: Home Assistant Release notification
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.denys
    data_template:
      title: '🎉 New Home Assistant Release'
      message: "Home Assistant  {{ state_attr('binary_sensor.updater', 'newest_version') }}  is now available."
