esphome:
  name: living-room-ac
  platform: ESP8266
  board: esp12e

# Enable logging
logger:
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'Living-Room-AC Fallback Hotspot'
    password: !secret living_room_ac_password

captive_portal:

# Optional (if you want modify settings)
midea_dongle:
  strength_icon: true

# Main settings
climate:
  - platform: midea_ac
    name: 'Living Room AC'
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    beeper: false
    custom_fan_modes:
      - SILENT
      - TURBO
    preset_eco: true
    preset_sleep: true
    preset_boost: true
    swing_horizontal: true
    swing_both: true
    outdoor_temperature:
      name: 'Living Room AC Temperature'
    power_usage:
      name: 'Living Room AC Power'
    humidity_setpoint:
      name: 'Living Room AC Humidity'
