homeassistant: true
# TODO: Add these files
# devices: devices.yaml
# groups: groups.yaml
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost:1883'
  user: !secret mqtt_user
  password: !secret mqtt_password
serial:
  port: /dev/ttyACM0
frontend:
  port: 8099
