homeassistant: true
devices: devices.yaml
groups: groups.yaml
mqtt:
  base_topic: zigbee2mqtt
  include_device_information: true
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
advanced:
  channel: 15
  last_seen: ISO_8601_local
  log_level: info
