name: Home Assistant CI

on:
  push:
    - main
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home-assistant:
    name: Home Assistant Config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['stable', 'beta', 'dev']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Prepare Stubs
        run: cp -R home-assistant/stubs/* ./home-assistant

      - name: Home Assistant Check
        uses: frenck/action-home-assistant@v1
        with:
          path: home-assistant
          secrets: home-assistant/secrets.example.yaml
          version: '${{ matrix.version }}'
