name: Home Assistant

on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home-assistant-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Prepare Stubs
        run: cp -R homeassistant/.stubs/* homeassistant/

      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --version

      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config homeassistant --script check_config --info all

  home-assistant-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Prepare Stubs
        run: cp -R homeassistant/.stubs/* homeassistant/
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: python -m homeassistant --config homeassistant --script check_config --info all
